version: 2
jobs:
  build:
    docker:
      # Note: Raspbian stretch actually has Python 3.5.3, but CircleCI's images
      # don't offer exactly that combination. We go with the closest we can,
      # even this is likely on the wrong patch version.
      - image: python:3.5-stretch

    steps:
      - checkout
      - run: python3 -m venv venv

      - run:
          name: install sb-vision
          command: |
            apt-get update -y
            apt-get install -y libcv-dev libopencv-photo-dev libopencv-contrib-dev libusb-1.0.0-dev
            venv/bin/pip install git+https://github.com/sourcebots/sb-vision

      - run:
          name: install ourselves
          command: venv/bin/pip install -e .

      - run: venv/bin/python3 -m unittest

      - run: venv/bin/pip install -r script/linting/requirements.txt
      - run:
          command: script/linting/lint
          environment:
            FLAKE8: venv/bin/flake8
